# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DfirCli < Formula
  desc "DFIR Lab CLI — digital forensics and incident response toolkit"
  homepage "https://dfir-lab.ch"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ForeGuards/dfir-cli/releases/download/v0.1.0/dfir-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "d3c408ddba975d0ed0472473b93fdf7f71d408f42fa80ad588b20584749afc0b"

      define_method(:install) do
        bin.install "dfir-cli"

        bash_completion.install "completions/dfir-cli.bash" => "dfir-cli"
        zsh_completion.install "completions/_dfir-cli"
        fish_completion.install "completions/dfir-cli.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ForeGuards/dfir-cli/releases/download/v0.1.0/dfir-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "7ed34987e93cb5645555ff9d50d5e1a548fdb8b62e00166f2b92a74cb6bab07f"

      define_method(:install) do
        bin.install "dfir-cli"

        bash_completion.install "completions/dfir-cli.bash" => "dfir-cli"
        zsh_completion.install "completions/_dfir-cli"
        fish_completion.install "completions/dfir-cli.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ForeGuards/dfir-cli/releases/download/v0.1.0/dfir-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "931f1317aae81fba5aa220ce3232401e6dc927651c487b1b96742d50ffa94b69"
      define_method(:install) do
        bin.install "dfir-cli"

        bash_completion.install "completions/dfir-cli.bash" => "dfir-cli"
        zsh_completion.install "completions/_dfir-cli"
        fish_completion.install "completions/dfir-cli.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ForeGuards/dfir-cli/releases/download/v0.1.0/dfir-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "3b99236be772ea8f010a001b413442e79696a401446c565f976a759bb3f8ab01"
      define_method(:install) do
        bin.install "dfir-cli"

        bash_completion.install "completions/dfir-cli.bash" => "dfir-cli"
        zsh_completion.install "completions/_dfir-cli"
        fish_completion.install "completions/dfir-cli.fish"
      end
    end
  end

  test do
    system "#{bin}/dfir-cli", "--version"
  end
end
