# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DfirCli < Formula
  desc "DFIR Lab CLI — digital forensics and incident response toolkit"
  homepage "https://dfir-lab.ch"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ForeGuards/dfir-cli-releases/releases/download/v0.1.0/dfir-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "5562570f2d5624752f0d4141ada7d0aa8ca786f13d3c5be8e15f15d9a0f6a27e"

      define_method(:install) do
        bin.install "dfir-cli"

        bash_completion.install "completions/dfir-cli.bash" => "dfir-cli"
        zsh_completion.install "completions/_dfir-cli"
        fish_completion.install "completions/dfir-cli.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ForeGuards/dfir-cli-releases/releases/download/v0.1.0/dfir-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "5848f4fe23d02dbe041065c21b4a9455e2aa93a9dab8dd1db701f680d0a3a771"

      define_method(:install) do
        bin.install "dfir-cli"

        bash_completion.install "completions/dfir-cli.bash" => "dfir-cli"
        zsh_completion.install "completions/_dfir-cli"
        fish_completion.install "completions/dfir-cli.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ForeGuards/dfir-cli-releases/releases/download/v0.1.0/dfir-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "b41c3eb4d90ca9c0b9d498caecc2b83f86bcb4a1bf9b09d3203b33e6b783f615"
      define_method(:install) do
        bin.install "dfir-cli"

        bash_completion.install "completions/dfir-cli.bash" => "dfir-cli"
        zsh_completion.install "completions/_dfir-cli"
        fish_completion.install "completions/dfir-cli.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ForeGuards/dfir-cli-releases/releases/download/v0.1.0/dfir-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "84af7adc2dcd5debcd038ea5d789472b9c6faff7a5e02dac7eccd3ee562b8042"
      define_method(:install) do
        bin.install "dfir-cli"

        bash_completion.install "completions/dfir-cli.bash" => "dfir-cli"
        zsh_completion.install "completions/_dfir-cli"
        fish_completion.install "completions/dfir-cli.fish"
      end
    end
  end

  test do
    system "#{bin}/dfir-cli", "--version"
  end
end
